apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo
  labels:
    run: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - image: bluezd/k8s-demo:623261e4ef245744936d1e86569e68d183031e53
        imagePullPolicy: Always 
        name: demo
        command: ["jekyll", "serve"]
        ports:
        - containerPort: 4000 
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demosvc
spec:
    type: NodePort
    ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
    selector:
      run: demo
